# init hexo-theme-next config
favicon:
  small: /images/favicon-16x16-next.png
  medium: /images/favicon-32x32-next.png
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg
  
keywords: "Hexo, NexT"

rss:

footer:
  since: 2018
  icon: user
  copyright:
  powered: false
  theme:
    enable: false
    version: false
	
canonical: true
seo: false
index_with_subtitle: false

menu:
  home: / || home
  archives: /archives/ || archive
  tags: /tags/ || tag
  photos: /photos/ || book
  guestbook: /guestbook/ || commenting
  about: /about/ || user
  
menu_icons:
  enable: true

# ????
scheme: Pisces

# ????
font:
  enable: true
  host:
  global:
    external: true
    family: Monda
  headings:
    external: true
    family: Roboto Slab
  posts:
    external: true
    family:
  logo:
    external: true
    family: Lobster Two
    size:
  codes:
    external: true
    family: PT Mono
    size:
    
social:
  GitHub: https://github.com/nightalexly || github
  ZhiHu: https://www.zhihu.com/people/luis-59-9/activities || question-circle-o
  WangYi: http://music.163.com/#/user/home?id=262759259 || pinterest-square
  
social_icons:
  enable: true
  icons_only: false

links_icon: link
links_title: Links
links_layout: inline
links:
  Site diary: https://notes.rtime.xin/2017/06/14/Site%20diary/
  Handling: https://notes.rtime.xin/2017/06/13/%E5%BE%85%E5%A4%84%E7%90%86/
  Lables: https://notes.rtime.xin/lables/
  Cycling: https://notes.rtime.xin/2017/01/01/%E9%AA%91%E8%A1%8C%E4%B9%8B%E6%97%85/
  Motto: https://notes.rtime.xin/2017/06/13/%E5%90%8D%E8%A8%80%E8%AD%A6%E5%8F%A5/

toc:
  enable: true
  number: true
  wrap: false
  
sidebar:
  position: left
  display: post  
  offset: 12
  # ????
  offset_float: 0
  b2t: false
  # ????
  scrollpercent: true
  onmobile: false

scroll_to_more: true
excerpt_description: true

auto_excerpt:
  # ????
  enable: true
  length: 150

post_meta:
  item_text: true
  created_at: true
  updated_at: false
  categories: true

post_wordcount:
  item_text: true
  wordcount: false
  min2read: false
  totalcount: false
  separated_meta: true

# ????
post_copyright:
  enable: true
  license: CC BY-NC-SA 3.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/3.0/

mobile_layout_economy: false
android_chrome_color: "#222"

custom_logo:
  enabled: false
  image:

highlight_theme: normal

mathjax:
  enable: false
  per_page: false
  # ????
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML

han: false

disqus:
  enable: false
  shortname:
  count: true

changyan:
  enable: false
  appid:
  appkey:

duoshuo_info:
  ua_enable: true
  admin_enable: false
  user_id: 0

facebook_sdk:
  enable:       false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true  

facebook_comments_plugin:
  enable:       false
  num_of_posts: 10    # min posts num is 1
  width:        100%  # default width is 550px
  scheme:       light # default scheme is light (light or dark)
  
vkontakte_api:
  enable:       false
  app_id:       #<app_id>
  like:         true
  comments:     true
  num_of_posts: 10
  
rating:
  enable: false
  id:     #<app_id>
  color:  fc6423
  
leancloud_visitors:
  enable: false
  app_id: #<app_id>
  app_key: #<app_key>
  
busuanzi_count:
  enable: false
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:

baidu_push: false

calendar:
  enable: false
  calendar_id: <required>
  api_key: <required>
  orderBy: startTime
  offsetMax: 24
  offsetMin: 4
  timeZone:
  showDeleted: false
  singleEvents: true
  maxResults: 250
  
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# ????
local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1
  
exturl: false

note:
  style: simple
  icons: false
  border_radius: 3
  light_bg_offset: 0

label: true

tabs:
  enable: true
  transition:
    tabs: false
    labels: true
  border_radius: 0
  
motion:
  enable: false
  async: false
  transition:
    post_block: fadeIn
    post_header: slideDownIn
    post_body: slideDownIn
    coll_header: slideLeftIn
    sidebar: slideUpIn
	
fancybox: true
pace: false
pace_theme: pace-theme-minimal
# ????
canvas_nest: true
three_waves: false
canvas_lines: false
canvas_sphere: false

canvas_ribbon:
  enable: false
  size: 300
  alpha: 0.6
  zIndex: -1
  
vendors:
   # ????
  _internal: vendors
  jquery: //cdn.jsdelivr.net/jquery/2.1.3/jquery.min.js
  fancybox: //cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.pack.js
  fancybox_css: //cdn.jsdelivr.net/fancybox/2.1.5/jquery.fancybox.min.css
  fastclick: //cdn.jsdelivr.net/fastclick/1.0.6/fastclick.min.js
  lazyload: //cdn.jsdelivr.net/jquery.lazyload/1.9.3/jquery.lazyload.min.js
  velocity: //cdn.jsdelivr.net/velocity/1.2.3/velocity.min.js
  velocity_ui: //cdn.jsdelivr.net/velocity/1.2.3/velocity.ui.min.js
  ua_parser: //cdn.jsdelivr.net/ua-parser.js/0.7.10/ua-parser.min.js
  fontawesome: //maxcdn.bootstrapcdn.com/font-awesome/4.6.2/css/font-awesome.min.css
  algolia_instant_js:
  algolia_instant_css:
  pace:
  pace_css:
  canvas_nest: //cdn.bootcss.com/canvas-nest.js/1.0.0/canvas-nest.min.js
  three:
  three_waves:
  canvas_lines:
  canvas_sphere:
  canvas_ribbon:
  han:
  needMoreShare2:

css: css
js: js
images: images

version: 5.1.4

reward_comment: 坚持原创技术分享，您的支持将鼓励我继续创作！
wechatpay: /images/wechatpay.jpg
alipay: /images/alipay.jpg

passage_end_tag:
  enabled: true