# my blog init config

# basic
title: run time
subtitle: stay hungry stay foolish 
description: stay hungry stay foolish 
keywords:
author: Luis Yang
language: zh-Hans
timezone:

# url
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
photo_dir: photos
i18n_dir: :lang
skip_render: README.md

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
per_page: 10
pagination_dir: page

# Extensions
theme: next

# Deployment
deploy:
  type: git
  repo: https://github.com/NightAlexLy/NightAlexLy.github.io.git
  branch: master
  
search:
  path: search.xml
  field: post
  format: html
  limit: 10000
  
avatar: /images/avatar.jpg

social:
  GitHub: https://github.com/nightalexly
  ZhiHu: https://www.zhihu.com/people/luis-59-9/activities
  WangYi: http://music.163.com/#/user/home?id=262759259
  
index_generator:
  per_page: 5

archive_generator:
  per_page: 10
  yearly: true
  monthly: true

tag_generator:
  per_page: 10

photo_generator:
  per_page: 3
  yearly: true
  monthly: true